const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={teamScores:{Red:0,Blue:0,Green:0,Yellow:0},team:'Red',individual:{robot:0,order:0,think:0},completed:{robot:false,order:false,think:false}};
const teamMCQ=[
 ['What is an algorithm?',['A list of random ideas','A clear set of steps to solve a problem','A computer part','A picture'],1],
 ['Which quality is most important in an algorithm?',['It is colourful','It is as long as possible','The steps are clear and ordered','It uses difficult words'],2],
 ['What should you do when an algorithm fails?',['Ignore it','Debug the steps','Start a different subject','Add random steps'],1],
 ['Which comes first when solving a problem?',['Test','Plan','Celebrate','Delete'],1],
 ['A recipe is an example of…',['An algorithm','A password','A device','A score'],0]
];
const teamOrder=[['Make toast',['Put bread in toaster','Press toaster lever','Wait for toast','Take toast out']],['Brush your teeth',['Put toothpaste on brush','Brush teeth','Rinse mouth','Put toothbrush away']],['Send a message',['Open messaging app','Choose a contact','Type message','Press send']]];
const individualOrder=[['Wash your hands',['Turn on water','Wet hands','Add soap','Scrub hands','Rinse hands','Dry hands']],['Plant a seed',['Make a small hole','Put seed in soil','Cover seed','Water it','Place in sunlight']],['Pack your school bag',['Check timetable','Collect books','Put books in bag','Add pencil case','Zip the bag']]];
let teamMCQIndex=0,teamOrderIndex=0,teamRobot=null,indRobot=null;
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===id));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='scores')renderScores();if(id==='certificate')renderCertificate()}
$$('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));$$('.nav-btn').forEach(b=>b.onclick=()=>showView(b.dataset.view));
$('#startTeam').onclick=()=>{state.team=$('#teamName').value;$('#teamGame').classList.remove('hidden');teamMCQIndex=0;teamOrderIndex=0;renderTeamMCQ();};
$('#teamName').onchange=e=>state.team=e.target.value;
$$('#teamLevelTabs .level-tab').forEach(b=>b.onclick=()=>{const l=b.dataset.level;$$('#teamLevelTabs .level-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.level-panel').forEach(x=>x.classList.remove('active-level'));$(`#teamLevel${l}`).classList.add('active-level');if(l==='1')renderTeamMCQ();if(l==='2')renderTeamOrder();if(l==='3')renderTeamRobot();});
function addTeam(n){state.teamScores[state.team]+=n;$('#teamTotal').textContent=state.teamScores[state.team];}
function renderTeamMCQ(){const q=teamMCQ[teamMCQIndex];$('#teamLevel1').innerHTML=`<div class="question-meta"><span>Level 1 · MCQ</span><span>Question ${teamMCQIndex+1}/${teamMCQ.length} · +10</span></div><div class="question"><h3>${q[0]}</h3><div class="answers">${q[1].map((a,i)=>`<button class="answer" data-i="${i}">${a}</button>`).join('')}</div><div id="tmFeedback" class="feedback"></div></div>`;$$('#teamLevel1 .answer').forEach(b=>b.onclick=()=>{if(b.disabled)return;const ok=+b.dataset.i===q[2];$$('#teamLevel1 .answer').forEach(x=>x.disabled=true);b.classList.add(ok?'correct':'wrong');$('#tmFeedback').textContent=ok?'Correct! +10 points':'Not quite — no points this time.';if(ok)addTeam(10);setTimeout(()=>{teamMCQIndex++;if(teamMCQIndex<teamMCQ.length)renderTeamMCQ();else $('#teamLevel1').innerHTML=`<h3>Level 1 complete! 🎉</h3><p>Your team earned points from the MCQ round.</p><button class="primary" onclick="document.querySelector('[data-level=2]').click()">Go to Level 2 →</button>`},650)});}
function orderMarkup(items){return `<div class="order-list">${items.map((x,i)=>`<div class="order-item" draggable="true" data-value="${encodeURIComponent(x)}"><span class="number">${i+1}</span>${x}</div>`).join('')}</div>`}
function wireDrag(container){let drag;$$('.order-item',container).forEach(el=>{el.ondragstart=()=>{drag=el;el.classList.add('dragging')};el.ondragend=()=>el.classList.remove('dragging');el.ondragover=e=>{e.preventDefault();const r=el.getBoundingClientRect();if(e.clientY<r.top+r.height/2)el.before(drag);else el.after(drag)}})}
function renderTeamOrder(){const q=teamOrder[teamOrderIndex];const shuffled=[...q[1]].sort(()=>Math.random()-.5);$('#teamLevel2').innerHTML=`<div class="question-meta"><span>Level 2 · In Order</span><span>Challenge ${teamOrderIndex+1}/${teamOrder.length} · +20</span></div><h3>Put the steps in the correct order.</h3>${orderMarkup(shuffled)}<div class="feedback" id="toFeedback"></div><div class="action-row"><span>Work as a team — agree before checking.</span><button class="primary" id="checkTeamOrder">Check Order</button></div>`;wireDrag($('#teamLevel2'));$('#checkTeamOrder').onclick=()=>{const got=$$('#teamLevel2 .order-item').map(x=>decodeURIComponent(x.dataset.value));const ok=got.every((x,i)=>x===q[1][i]);$('#toFeedback').textContent=ok?'Correct! +20 points':'Try again — check which step should happen first.';if(ok){addTeam(20);$('#checkTeamOrder').disabled=true;setTimeout(()=>{teamOrderIndex++;if(teamOrderIndex<teamOrder.length)renderTeamOrder();else $('#teamLevel2').innerHTML='<h3>Level 2 complete! 🔢</h3><p>Excellent sequencing.</p><button class="primary" onclick="document.querySelector(\'[data-level=3]\').click()">Go to Level 3 →</button>'},700)}}}
function makeRobot(target){return {x:0,y:4,dir:0,target,steps:[],done:false}};
const dirs=[[0,-1],[1,0],[0,1],[-1,0]], arrows=['↑','→','↓','←'];
function renderRobot(container,robot,title,points,label,callback){container.innerHTML=`<div class="question-meta"><span>${label}</span><span>${points} points</span></div><h3>${title}</h3><div class="robot-wrap"><div><div class="robot-board" id="${container.id}Board"></div><div class="action-row"><span>Commands: ${robot.steps.join(' → ')||'none'}</span><button class="primary" id="${container.id}Test">Test Robot</button></div></div><div class="commands"><button class="command-btn" data-c="F">⬆ Forward</button><button class="command-btn" data-c="L">↶ Turn Left</button><button class="command-btn" data-c="R">↷ Turn Right</button><button class="command-btn" id="${container.id}Clear">Clear</button></div></div><div id="${container.id}Feedback" class="feedback"></div>`;const board=$(`#${container.id}Board`);for(let y=0;y<5;y++)for(let x=0;x<5;x++){const c=document.createElement('div');c.className='cell';if(x===robot.target.x&&y===robot.target.y)c.classList.add('target');if(x===robot.x&&y===robot.y)c.classList.add('robot');c.textContent=x===robot.x&&y===robot.y?'🤖':(x===robot.target.x&&y===robot.target.y?'⭐':'');board.appendChild(c)};$$(`#${container.id} .command-btn[data-c]`).forEach(b=>b.onclick=()=>{if(robot.steps.length<12)robot.steps.push(b.dataset.c);renderRobot(container,robot,title,points,label,callback)});$(`#${container.id}Clear`).onclick=()=>{robot.steps=[];renderRobot(container,robot,title,points,label,callback)};$(`#${container.id}Test`).onclick=()=>{let x=0,y=4,d=0;for(const c of robot.steps){if(c==='L')d=(d+3)%4;if(c==='R')d=(d+1)%4;if(c==='F'){x+=dirs[d][0];y+=dirs[d][1];if(x<0||x>4||y<0||y>4)break}}const ok=x===robot.target.x&&y===robot.target.y;const fb=$(`#${container.id}Feedback`);fb.textContent=ok?`Success! +${points} points`:`Not there yet. You reached (${x+1}, ${y+1}). Debug your commands.`;if(ok&&!robot.done){robot.done=true;callback(points)}}}
function renderTeamRobot(){teamRobot=makeRobot({x:4,y:0});renderRobot($('#teamLevel3'),teamRobot,'Guide the robot to the star. Use as few commands as possible.',40,'Level 3 · Robot Game',n=>{addTeam(n);setTimeout(()=>{$('#teamLevel3').innerHTML=`<h3>Team Quest Complete! 🏆</h3><p>You finished all three levels. Your accumulated team score is <strong>${state.teamScores[state.team]}</strong>.</p><button class="primary" onclick="showView('scores')">See Scoreboard →</button>`},500)})}
function switchIndividual(game){$$('.game-tab').forEach(b=>b.classList.toggle('active',b.dataset.game===game));['robot','order','think'].forEach(x=>$(`#individual${x[0].toUpperCase()+x.slice(1)}`).classList.toggle('hidden',x!==game));if(game==='robot')renderIndividualRobot();if(game==='order')renderIndividualOrder();if(game==='think')renderThink()}
$$('.game-tab').forEach(b=>b.onclick=()=>switchIndividual(b.dataset.game));
function addIndividual(game,n){if(n>state.individual[game])state.individual[game]=n;updateIndividualScore()}
function updateIndividualScore(){$('#individualTotal').textContent=Object.values(state.individual).reduce((a,b)=>a+b,0);$('#individualScoreBig').textContent=Object.values(state.individual).reduce((a,b)=>a+b,0)}
function renderIndividualRobot(){indRobot=makeRobot({x:4,y:4});renderRobot($('#individualRobot'),indRobot,'Can you reach the star? Build your own command sequence.',40,'Game 1 · Robot Game',n=>{addIndividual('robot',n);state.completed.robot=true})}
function renderIndividualOrder(){const q=individualOrder[0];const shuffled=[...q[1]].sort(()=>Math.random()-.5);$('#individualOrder').innerHTML=`<div class="question-meta"><span>Game 2 · In Order</span><span>+30 points</span></div><h3>${q[0]} — arrange the steps.</h3>${orderMarkup(shuffled)}<div class="feedback" id="ioFeedback"></div><div class="action-row"><span>Drag the steps into the correct sequence.</span><button class="primary" id="checkIO">Check Order</button></div>`;wireDrag($('#individualOrder'));$('#checkIO').onclick=()=>{const got=$$('#individualOrder .order-item').map(x=>decodeURIComponent(x.dataset.value));const ok=got.every((x,i)=>x===q[1][i]);$('#ioFeedback').textContent=ok?'Correct! +30 points':'Not quite. Try again.';if(ok){addIndividual('order',30);state.completed.order=true;$('#checkIO').disabled=true}}}
function renderThink(){$('#individualThink').innerHTML=`<div class="question-meta"><span>Game 3 · Think of Any</span><span>Up to 30 points</span></div><h3>Create an algorithm for any everyday task.</h3><p>Choose something such as making a sandwich, getting ready for school, or scoring a goal. Give it a clear goal and at least 5 ordered steps.</p><div class="think-form"><input id="thinkTitle" placeholder="My algorithm is for…"><textarea id="thinkSteps" placeholder="1. …\n2. …\n3. …\n4. …\n5. …"></textarea><button class="primary" id="checkThink">Submit My Algorithm</button></div><div id="thinkFeedback" class="feedback"></div>`;$('#checkThink').onclick=()=>{const title=$('#thinkTitle').value.trim(),lines=$('#thinkSteps').value.split('\n').map(x=>x.replace(/^\s*\d+[.)-]?\s*/,'').trim()).filter(Boolean);let score=0;if(title)score+=5;if(lines.length>=3)score+=10;if(lines.length>=5)score+=10;if(lines.length>=7)score+=5;const f=$('#thinkFeedback');if(lines.length<3){f.textContent='Add at least 3 clear steps before submitting.';return}addIndividual('think',score);state.completed.think=true;f.innerHTML=`You earned <span class="score-gain">${score} points</span>. ${lines.length>=5?'Great algorithm!':'Add more steps next time for a higher score.'}`;$('#checkThink').disabled=true}}
function renderScores(){const rows=Object.entries(state.teamScores).sort((a,b)=>b[1]-a[1]);$('#teamBoard').innerHTML=rows.map(([n,s],i)=>`<div class="team-row"><span>${i===0&&s>0?'🏆 ':''}${n} Team</span><strong>${s}</strong></div>`).join('');const top=rows[0];$('#winnerBox').classList.toggle('hidden',!(top&&top[1]>0));if(top&&top[1]>0)$('#winnerBox').textContent=`Current highest team: ${top[0]} Team · ${top[1]} points`;updateIndividualScore()}
function renderCertificate(){const name=prompt('Enter your name for the certificate:','Algorithm Explorer')||'Algorithm Explorer';$('#certificateName').textContent=name;$('#certificateScore').textContent=Object.values(state.individual).reduce((a,b)=>a+b,0);$('#certificateDate').textContent=new Date().toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'})}
$('#certificateBtn').onclick=()=>{renderCertificate();showView('certificate')};
renderTeamMCQ();renderIndividualRobot();updateIndividualScore();
