import {firebaseReady,db,ref,get,update,onValue} from './firebase.js';
import {TEAMS,TEAM_INFO,MCQ,ORDERS,ROBOTS} from './data.js';
const $=id=>document.getElementById(id);let code='',team='',student='',game=null,localKey='';
$('teamPicker').innerHTML=TEAMS.map(t=>`<button data-team="${t}">${TEAM_INFO[t].emoji} ${TEAM_INFO[t].name}</button>`).join('');document.querySelectorAll('[data-team]').forEach(b=>b.onclick=()=>{team=b.dataset.team;document.querySelectorAll('[data-team]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
const msg=t=>$('joinMsg').textContent=t;
async function join(){if(!firebaseReady)return msg('Firebase is not configured yet. Ask the teacher to finish setup.');code=$('gameCode').value.trim().toUpperCase();student=$('studentName').value.trim()||'Student';if(!code||!team)return msg('Enter the game code and choose a team.');const snap=await get(ref(db,`games/${code}`));if(!snap.exists())return msg('Game not found. Check the code.');game=snap.val();if(!game.teams?.[team])return msg('That team is not in this game.');localKey=`${code}:${team}`;await update(ref(db,`games/${code}/teams/${team}`),{players:(game.teams[team].players||0)+1});$('join').classList.add('hidden');$('game').classList.remove('hidden');onValue(ref(db,`games/${code}`),s=>{game=s.val();render()})}
function render(){if(!game)return;$('myTeam').textContent=`${TEAM_INFO[team].emoji} ${TEAM_INFO[team].name}`;$('myScore').textContent=game.teams?.[team]?.score||0;$('myLevel').textContent=game.level==='waiting'?'Waiting':game.level.toUpperCase();if(game.level==='mcq')return renderMCQ();if(game.level==='order')return renderOrder();if(game.level==='robot')return renderRobot();$('play').innerHTML=game.level==='finished'?'<h2>🎉 Team Challenge Complete</h2><p>Check the teacher screen for the final winner.</p>':'<h2>Waiting for your teacher…</h2><p class="muted">The next challenge will appear here.</p>'}
function already(type,i){return !!game.teams?.[team]?.answers?.[`${type}-${i}`]}
async function submit(type,i,points,extra){if(already(type,i))return false;const key=`${type}-${i}`;const current=game.teams[team]||{};const answers={...(current.answers||{}),[key]:{student,points,time:Date.now(),...extra}};await update(ref(db,`games/${code}/teams/${team}`),{score:(current.score||0)+points,answers});return true}
function renderMCQ(){const i=game.index%MCQ.length,q=MCQ[i];$('play').innerHTML=`<span class="eyebrow">LEVEL 1 · MCQ</span><h2>${q.q}</h2><div class="answers">${q.options.map((x,j)=>`<button data-a="${j}">${x}</button>`).join('')}</div><p id="feedback" class="message"></p>`;if(already('mcq',i)){disableAnswered();return}$('play').querySelectorAll('[data-a]').forEach(b=>b.onclick=async()=>{const ok=+b.dataset.a===q.answer;const accepted=await submit('mcq',i,ok?q.points:0,{correct:ok});if(!accepted)return;disableAnswered();b.classList.add(ok?'correct':'wrong');$('feedback').textContent=ok?`Correct! +${q.points} points`:'Not quite. Your team can try the next question.'})}
function disableAnswered(){document.querySelectorAll('#play button').forEach(b=>b.disabled=true);const f=$('feedback');if(f)f.textContent='This team has already submitted this question. Wait for the next one.'}
function renderOrder(){const i=game.index%ORDERS.length,q=ORDERS[i];let items=[...q.steps].sort(()=>Math.random()-.5);$('play').innerHTML=`<span class="eyebrow">LEVEL 2 · IN ORDER</span><h2>${q.title}</h2><p>Drag the steps into the correct order.</p><div id="orderList" class="orderlist">${items.map(s=>`<div class="orderitem" draggable="true" data-step="${s}">${s}</div>`).join('')}</div><button id="submit" class="primary">Submit Order</button><p id="feedback" class="message"></p>`;if(already('order',i)){disableAnswered();return}const list=$('orderList');let drag=null;list.querySelectorAll('.orderitem').forEach(el=>{el.ondragstart=()=>drag=el;el.ondragover=e=>e.preventDefault();el.ondrop=()=>{if(drag&&drag!==el)list.insertBefore(drag,el)}});$('submit').onclick=async()=>{const got=[...list.children].map(x=>x.dataset.step),ok=got.every((x,j)=>x===q.steps[j]);if(!ok){$('feedback').textContent='Not yet — check the order and try again.';return}await submit('order',i,q.points,{correct:true});disableAnswered();$('feedback').textContent=`Correct! +${q.points} points`}}
function renderRobot(){const i=game.index%ROBOTS.length,q=ROBOTS[i];let pos=[...q.start],dir=0,moves=[];const dirs=[[-1,0],[0,1],[1,0],[0,-1]],arrows=['↑','→','↓','←'];const draw=()=>{$('play').innerHTML=`<span class="eyebrow">LEVEL 3 · ROBOT GAME</span><h2>${q.name}</h2><p>F = forward · L = turn left · R = turn right</p><div class="robot">${Array.from({length:q.size*q.size},(_,n)=>{const r=Math.floor(n/q.size),c=n%q.size,blocked=q.blocked.some(x=>x[0]===r&&x[1]===c);let cls='cell';if(blocked)cls+=' blocked';if(r===q.goal[0]&&c===q.goal[1])cls+=' goal';if(r===pos[0]&&c===pos[1])cls+=' bot';return `<div class="${cls}">${r===pos[0]&&c===pos[1]?'🤖':r===q.goal[0]&&c===q.goal[1]?'⭐':''}</div>`}).join('')}</div><p><b>Direction:</b> ${arrows[dir]} &nbsp; <b>Program:</b> ${moves.join(' ')||'—'}</p><div class="robotbuttons"><button data-c="F">F</button><button data-c="L">L</button><button data-c="R">R</button><button id="test" class="primary">Test</button><button id="clear">Clear</button></div><p id="feedback" class="message"></p>`;if(already('robot',i)){disableAnswered();return}document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{const c=b.dataset.c;moves.push(c);if(c==='L')dir=(dir+3)%4;if(c==='R')dir=(dir+1)%4;if(c==='F'){const nr=pos[0]+dirs[dir][0],nc=pos[1]+dirs[dir][1];if(nr>=0&&nr<q.size&&nc>=0&&nc<q.size&&!q.blocked.some(x=>x[0]===nr&&x[1]===nc)){pos=[nr,nc]}else{$('feedback').textContent='🚧 Blocked! Debug your program.'}}draw()});$('clear').onclick=()=>{pos=[...q.start];dir=0;moves=[];draw()};$('test').onclick=async()=>{const ok=pos[0]===q.goal[0]&&pos[1]===q.goal[1];if(!ok){$('feedback').textContent='Keep debugging — the robot has not reached the goal.';return}await submit('robot',i,q.points,{correct:true,program:moves.join('')});disableAnswered();$('feedback').textContent=`🎉 Success! +${q.points} points`}};draw()}
$('joinBtn').onclick=join;
