import {firebaseReady,db,ref,get,update,onValue,runTransaction,push} from './firebase.js';
import {TEAMS,TEAM_INFO,MCQ,ORDERS,ROBOTS} from './data.js';
const $=id=>document.getElementById(id);let code='',team='',student='',game=null,participantId='',timer=null,lastCelebration=false;
$('teamPicker').innerHTML=TEAMS.map(t=>`<button data-team="${t}">${TEAM_INFO[t].emoji} ${TEAM_INFO[t].name}</button>`).join('');document.querySelectorAll('[data-team]').forEach(b=>b.onclick=()=>{team=b.dataset.team;document.querySelectorAll('[data-team]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
const msg=t=>$('joinMsg').textContent=t;
async function join(){if(!firebaseReady)return msg('Firebase is not configured yet. Ask your teacher to finish setup.');code=$('gameCode').value.trim().toUpperCase();student=$('studentName').value.trim();if(!code||!student||!team)return msg('Enter the game code, your name, and choose a team.');const snap=await get(ref(db,`games/${code}`));if(!snap.exists())return msg('Game not found. Check the code.');game=snap.val();if(!game.teams?.[team])return msg('That team is not in this game.');participantId=push(ref(db,`games/${code}/teams/${team}/participants`)).key;await update(ref(db,`games/${code}/teams/${team}/participants/${participantId}`),{name:student,joinedAt:Date.now()});$('join').classList.add('hidden');$('game').classList.remove('hidden');onValue(ref(db,`games/${code}`),s=>{game=s.val();render()});}
function team(){return game?.teams?.[team]||{};}
function render(){if(!game)return;const t=team();$('myTeam').textContent=`${TEAM_INFO[team].emoji} ${TEAM_INFO[team].name}`;$('myScore').textContent=t.score||0;$('myLevel').textContent=game.level==='waiting'?'WAITING':game.level==='finished'?'FINISHED':game.level.toUpperCase();const ch=t.challenge||{};const total=game.level==='mcq'?10:game.level==='order'||game.level==='robot'?5:0;$('myProgress').textContent=total?`${Math.min((ch.index||0)+1,total)}/${total}`:'—';clearInterval(timer);timer=null;if(game.level==='mcq'&&!ch.completed){renderMCQ();startTimer(ch);}else if(game.level==='order'&&!ch.completed)renderOrder();else if(game.level==='robot'&&!ch.completed)renderRobot();else{$('play').innerHTML=game.level==='finished'?'<div class="waiting"><div class="bigemoji">🏆</div><h2>Team Challenge Complete!</h2><p>Check the celebration on the teacher screen.</p></div>':'<div class="waiting"><div class="bigemoji">⏳</div><h2>Waiting for the next level…</h2><p>Your teacher will start the challenge when everyone is ready.</p></div>';}
 if(game.level==='finished'&&!lastCelebration){lastCelebration=true;showCelebration()}if(game.level!=='finished')lastCelebration=false;}
function startTimer(ch){const tick=async()=>{const left=Math.max(0,300000-(Date.now()-(ch.startedAt||Date.now())));const qLeft=Math.max(0,30000-(Date.now()-(ch.questionStartedAt||Date.now())));$('timer').textContent=`${String(Math.ceil(qLeft/1000)).padStart(2,'0')}s`;if(left<=0){await finishMCQIfNeeded();return}if(qLeft<=0)await timeoutMCQ();};tick();timer=setInterval(tick,250);}
async function timeoutMCQ(){const path=`games/${code}/teams/${team}`;await runTransaction(ref(db,path),t=>{if(!t||!t.challenge||t.challenge.completed)return t;const i=t.challenge.index||0;if(i>=MCQ.length){t.challenge.completed=true;return t}if(Date.now()-(t.challenge.questionStartedAt||0)<30000)return t;t.challenge.index=i+1;t.challenge.questionStartedAt=Date.now();if(t.challenge.index>=MCQ.length)t.challenge.completed=true;return t;});}
async function finishMCQIfNeeded(){const path=`games/${code}/teams/${team}`;await runTransaction(ref(db,path),t=>{if(!t?.challenge)return t;if(Date.now()-(t.challenge.startedAt||0)<300000)return t;t.challenge.completed=true;t.challenge.index=MCQ.length;return t;});}
function renderMCQ(){const t=team(),i=t.challenge?.index||0;if(i>=MCQ.length){return showDone('MCQ complete! 🎯','Your team has finished all 10 questions.');}const q=MCQ[i];$('play').innerHTML=`<div class="challengeHead"><div><span class="eyebrow">LEVEL 1 • MCQ</span><h2>Question ${i+1}</h2></div><div class="timer" id="timer">30s</div></div><div class="progress"><span style="width:${(i/10)*100}%"></span></div><h3 class="question">${q.q}</h3><div class="answers">${q.options.map((x,j)=>`<button data-a="${j}">${String.fromCharCode(65+j)}. ${x}</button>`).join('')}</div><p class="muted">30 seconds per question • 5 minutes total • First submission from your team is scored.</p>`;document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>submitMCQ(i,q,+b.dataset.a));}
async function submitMCQ(i,q,answer){const path=ref(db,`games/${code}/teams/${team}`);const result=await runTransaction(path,t=>{if(!t?.challenge||t.challenge.completed||t.challenge.index!==i)return t;const key=`mcq-${i}`;t.answers=t.answers||{};if(t.answers[key])return t;t.answers[key]={student,correct:answer===q.answer,points:answer===q.answer?100:0,time:Date.now()};t.score=(t.score||0)+(answer===q.answer?100:0);t.challenge.index=i+1;t.challenge.questionStartedAt=Date.now();if(t.challenge.index>=MCQ.length)t.challenge.completed=true;return t;});}
function renderOrder(){const t=team(),i=t.challenge?.index||0;if(i>=ORDERS.length)return showDone('In Order complete! 🔢','Your team finished all 5 sequences.');const q=ORDERS[i];let items=[...q.steps].sort(()=>Math.random()-.5);$('play').innerHTML=`<div class="challengeHead"><div><span class="eyebrow">LEVEL 2 • IN ORDER</span><h2>Sequence ${i+1}</h2></div><div class="points">100 pts</div></div><h3 class="question">${q.title}</h3><p>Drag the steps into the correct order. You only get one submission for this sequence.</p><div id="orderList" class="orderlist">${items.map(s=>`<div class="orderitem" draggable="true" data-step="${s}">☷ ${s}</div>`).join('')}</div><button id="submitOrder" class="primary">Submit Order</button><p id="orderFeedback" class="message"></p>`;const list=$('orderList');let drag=null;list.querySelectorAll('.orderitem').forEach(el=>{el.ondragstart=()=>drag=el;el.ondragover=e=>e.preventDefault();el.ondrop=()=>{if(drag&&drag!==el)list.insertBefore(drag,el)}});$('submitOrder').onclick=()=>submitOrder(i,q);}
async function submitOrder(i,q){const got=[...document.querySelectorAll('.orderitem')].map(x=>x.dataset.step);const ok=got.every((x,j)=>x===q.steps[j]);await runTransaction(ref(db,`games/${code}/teams/${team}`),t=>{if(!t?.challenge||t.challenge.index!==i||t.challenge.completed)return t;const key=`order-${i}`;t.answers=t.answers||{};if(t.answers[key])return t;t.answers[key]={student,correct:ok,points:ok?100:0,time:Date.now()};t.score=(t.score||0)+(ok?100:0);t.challenge.index=i+1;t.challenge.questionStartedAt=Date.now();if(t.challenge.index>=ORDERS.length)t.challenge.completed=true;return t;});}
function simulate(q,moves){let pos=[...q.start],dir=q.dir??1;const dirs=[[-1,0],[0,1],[1,0],[0,-1]];for(const c of moves){if(c==='L')dir=(dir+3)%4;if(c==='R')dir=(dir+1)%4;if(c==='F'){const nr=pos[0]+dirs[dir][0],nc=pos[1]+dirs[dir][1];if(nr<0||nr>=q.size||nc<0||nc>=q.size||q.blocked.some(x=>x[0]===nr&&x[1]===nc))return {pos,dir,blocked:true};pos=[nr,nc];}}return {pos,dir,blocked:false};}
function renderRobot(){const t=team(),i=t.challenge?.index||0;if(i>=ROBOTS.length)return showDone('Robot missions complete! 🤖','Your team finished all 5 robot missions.');const q=ROBOTS[i];let moves=[];const arrows=['↑','→','↓','←'];const draw=(feedback='')=>{const sim=simulate(q,moves);$('play').innerHTML=`<div class="challengeHead"><div><span class="eyebrow">LEVEL 3 • ROBOT GAME</span><h2>Mission ${i+1}</h2></div><div class="points">150 pts</div></div><h3 class="question">${q.name}</h3><p>Build a program, then press <b>Test</b>. The robot starts fresh each time.</p><div class="robot" style="--size:${q.size}">${Array.from({length:q.size*q.size},(_,n)=>{const r=Math.floor(n/q.size),c=n%q.size,blocked=q.blocked.some(x=>x[0]===r&&x[1]===c),bot=r===sim.pos[0]&&c===sim.pos[1],goal=r===q.goal[0]&&c===q.goal[1];return `<div class="cell ${blocked?'blocked':''} ${goal?'goal':''} ${bot?'bot':''}">${bot?'🤖':goal?'⭐':''}</div>`}).join('')}</div><div class="program"><span>Program</span><b>${moves.join(' ')||'—'}</b><em>${arrows[sim.dir]}</em></div><div class="robotbuttons"><button data-c="F">F</button><button data-c="L">↶ L</button><button data-c="R">↷ R</button><button id="test" class="primary">Test Program</button><button id="clear" class="secondary">Clear</button></div><p id="robotFeedback" class="message">${feedback}</p>`;document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{if(moves.length<30){moves.push(b.dataset.c);draw()}});$('clear').onclick=()=>{moves=[];draw()};$('test').onclick=()=>testRobot(i,q,moves)};draw();}
async function testRobot(i,q,moves){const sim=simulate(q,moves),ok=!sim.blocked&&sim.pos[0]===q.goal[0]&&sim.pos[1]===q.goal[1];if(!ok){renderRobot();setTimeout(()=>{$('robotFeedback').textContent=sim.blocked?'🚧 Blocked! Debug and test again.':'Not there yet — adjust your program and test again.'},0);return;}await runTransaction(ref(db,`games/${code}/teams/${team}`),t=>{if(!t?.challenge||t.challenge.index!==i||t.challenge.completed)return t;const key=`robot-${i}`;t.answers=t.answers||{};if(t.answers[key])return t;t.answers[key]={student,correct:true,points:150,program:moves.join(''),time:Date.now()};t.score=(t.score||0)+150;t.challenge.index=i+1;t.challenge.questionStartedAt=Date.now();if(t.challenge.index>=ROBOTS.length)t.challenge.completed=true;return t;});}
function showDone(title,text){$('play').innerHTML=`<div class="waiting"><div class="bigemoji">🎉</div><span class="eyebrow">TEAM PROGRESS</span><h2>${title}</h2><p>${text}</p><p class="muted">Move on when your next challenge appears.</p></div>`;}
function showCelebration(){const rows=Object.entries(game.teams||{}).sort((a,b)=>(b[1].score||0)-(a[1].score||0));if(!rows.length)return;const max=rows[0][1].score||0,wins=rows.filter(([,t])=>(t.score||0)===max),names=wins.flatMap(([id,t])=>Object.values(t.participants||{}).map(p=>p.name)).filter(Boolean);$('winnerTitle').textContent=wins.length>1?'Joint Winners!':`${TEAM_INFO[wins[0][0]].emoji} ${TEAM_INFO[wins[0][0]].name} Team Wins!`;$('winnerNames').textContent=names.length?`Players: ${names.join(', ')}`:'Congratulations!';$('winnerScore').textContent=`${max} points`;$('celebration').classList.remove('hidden');const box=$('confetti');box.innerHTML='';for(let i=0;i<70;i++){const s=document.createElement('i');s.className='confetti';s.style.left=Math.random()*100+'%';s.style.animationDelay=Math.random()*1.3+'s';s.style.setProperty('--x',(Math.random()*160-80)+'px');s.style.setProperty('--r',(Math.random()*720-360)+'deg');box.appendChild(s)}}
$('joinBtn').onclick=join;
