import { firebaseReady, db, ref, set, update, get, onValue } from './firebase-app.js';
import { TEAMS, TEAM_COLORS, teamName, teamMCQ, teamOrder, teamRobots } from './common.js';
const $=id=>document.getElementById(id); let code='',team='',student='',game=null,answered={};
$('teamPicker').innerHTML=TEAMS.map(t=>`<button data-team="${t}" style="border-color:${TEAM_COLORS[t]}">${teamName(t)}</button>`).join('');document.querySelectorAll('[data-team]').forEach(b=>b.onclick=()=>{team=b.dataset.team;document.querySelectorAll('[data-team]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
function show(msg){$('joinMsg').textContent=msg}
async function join(){if(!firebaseReady)return show('Teacher needs to add Firebase configuration first.');code=$('gameCode').value.trim().toUpperCase();student=$('studentName').value.trim()||'Student';if(!code||!team)return show('Enter the code and choose a team.');const snap=await get(ref(db,`games/${code}`));if(!snap.exists())return show('Game not found. Check the code.');const g=snap.val();if(!g.teams?.[team])return show('That team is not available.');await update(ref(db,`games/${code}/teams/${team}`),{players:(g.teams[team].players||0)+1});$('join').classList.add('hidden');$('game').classList.remove('hidden');onValue(ref(db,`games/${code}`),s=>{game=s.val();render()})}
function render(){if(!game)return;$('myTeam').textContent=teamName(team);$('myScore').textContent=game.teams?.[team]?.score||0;$('myLevel').textContent=game.level==='waiting'?'Waiting':game.level.toUpperCase();const p=$('play');if(game.level==='mcq')return renderMCQ(p);if(game.level==='order')return renderOrder(p);if(game.level==='robot')return renderRobot(p);if(game.level==='finished')return finish();p.innerHTML='<h2>Waiting for your teacher…</h2><p class="muted">Stay on this page. The next challenge will appear here.</p>'}
function renderMCQ(p){const i=game.qIndex||0,q=teamMCQ[i%teamMCQ.length];p.innerHTML=`<div class="eyebrow">LEVEL 1 · MCQ</div><div class="question">${q.q}</div><div class="answers">${q.options.map((x,j)=>`<button data-a="${j}">${x}</button>`).join('')}</div>`;p.querySelectorAll('[data-a]').forEach(b=>b.onclick=async()=>{if(answered[`mcq${i}`])return;answered[`mcq${i}`]=1;const pts=+b.dataset.a===q.a?q.points:0;await update(ref(db,`games/${code}/teams/${team}`),{score:(game.teams[team].score||0)+pts});p.querySelectorAll('button').forEach(x=>x.disabled=true);b.classList.add(pts?'correct':'wrong')})}
function renderOrder(p){const i=game.qIndex||0,q=teamOrder[i%teamOrder.length];let steps=[...q.steps].sort(()=>Math.random()-.5);p.innerHTML=`<div class="eyebrow">LEVEL 2 · IN ORDER</div><h2>${q.title}</h2><p>Drag the steps into the correct order.</p><div class="orderlist">${steps.map((s,j)=>`<div class="orderitem" draggable="true" data-step="${s}">${s}</div>`).join('')}</div><button class="primary" id="submitOrder">Submit Order</button>`;let drag;const list=p.querySelector('.orderlist');list.querySelectorAll('.orderitem').forEach(el=>{el.ondragstart=()=>drag=el;el.ondragover=e=>e.preventDefault();el.ondrop=()=>{if(drag&&drag!==el)list.insertBefore(drag,el)}});$('submitOrder').onclick=async()=>{const vals=[...list.children].map(x=>x.dataset.step);const ok=vals.every((v,j)=>v===q.steps[j]);if(answered[`order${i}`])return;answered[`order${i}`]=1;await update(ref(db,`games/${code}/teams/${team}`),{score:(game.teams[team].score||0)+(ok?q.points:0)});$('submitOrder').disabled=true;$('submitOrder').textContent=ok?`Correct! +${q.points}`:'Not quite — wait for the next challenge.'}}
function renderRobot(p){const i=game.qIndex||0,q=teamRobots[i%teamRobots.length];let pos=[...q.start],moves=[];const draw=()=>{p.innerHTML=`<div class="eyebrow">LEVEL 3 · ROBOT GAME</div><h2>${q.name}</h2><p>Use F, L, R to reach the green goal. F = forward, L/R = turn 90°.</p><div class="robot">${Array.from({length:q.size*q.size},(_,n)=>{const r=Math.floor(n/q.size),c=n%q.size,blocked=q.blocked.some(x=>x[0]===r&&x[1]===c);let cls='cell';if(blocked)cls+=' blocked';if(r===q.goal[0]&&c===q.goal[1])cls+=' goal';if(r===pos[0]&&c===pos[1])cls+=' bot';return `<div class="${cls}">${r===pos[0]&&c===pos[1]?'🤖':r===q.goal[0]&&c===q.goal[1]?'⭐':''}</div>`}).join('')}</div><p><b>Commands:</b> ${moves.join(' ')||'—'}</p><div class="robotbuttons"><button data-m="F">F</button><button data-m="L">L</button><button data-m="R">R</button><button id="test" class="primary">Test</button><button id="clear">Clear</button></div>`;p.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>{moves.push(b.dataset.m);if(b.dataset.m==='F'){pos[0]=Math.max(0,pos[0]-1)}draw()});$('clear').onclick=()=>{pos=[...q.start];moves=[];draw()};$('test').onclick=async()=>{const ok=pos[0]===q.goal[0]&&pos[1]===q.goal[1];if(answered[`robot${i}`])return;answered[`robot${i}`]=1;const pts=ok?100:0;await update(ref(db,`games/${code}/teams/${team}`),{score:(game.teams[team].score||0)+pts});$('test').textContent=ok?'Success! +100':'Not there yet'} };draw()}
function finish(){$('play').innerHTML=`<h2>Team Challenge Complete 🎉</h2><p>Your team finished with <b>${game.teams[team]?.score||0}</b> points.</p><p class="muted">Look at the teacher screen for the final winner.</p>`}
$('joinBtn').onclick=join;
