import {firebaseReady,db,ref,set,get,update,remove,onValue} from './firebase.js';
import {TEAMS,TEAM_INFO,MCQ,ORDERS,ROBOTS} from './data.js';
const $=id=>document.getElementById(id); let code='',game=null;
const makeCode=()=>Math.random().toString(36).slice(2,7).toUpperCase();
const say=t=>$('setupMsg').textContent=t;
function render(){if(!game)return;$('code').textContent=code;$('level').textContent=game.level==='waiting'?'WAITING':game.level.toUpperCase();$('questionNo').textContent=game.level==='waiting'?'—':`${(game.index||0)+1}`;const rows=Object.entries(game.teams||{}).sort((a,b)=>(b[1].score||0)-(a[1].score||0));$('scoreboard').innerHTML=rows.map(([id,t])=>`<div class="score"><span class="dot">${TEAM_INFO[id].emoji}</span><b>${TEAM_INFO[id].name}</b><span>${t.players||0} player(s)</span><strong>${t.score||0}</strong></div>`).join('');const top=rows[0];$('leader').textContent=top?`🏆 Highest score: ${TEAM_INFO[top[0]].name} Team · ${top[1].score||0} points`:'';let prompt='Waiting for a level.';if(game.level==='mcq')prompt=MCQ[game.index%MCQ.length].q;if(game.level==='order')prompt=`In Order: ${ORDERS[game.index%ORDERS.length].title}`;if(game.level==='robot')prompt=`Robot: ${ROBOTS[game.index%ROBOTS.length].name}`;if(game.level==='finished')prompt='🎉 Team Challenge finished. The highest score is the winner.';$('hostPrompt').textContent=prompt}
async function create(){if(!firebaseReady)return say('Firebase is not configured yet. Open firebase-config.js and add your project values.');code=makeCode();const n=+$('teamCount').value;const teams={};TEAMS.slice(0,n).forEach(t=>teams[t]={score:0,players:0,answers:{}});game={level:'waiting',index:0,teams};await set(ref(db,`games/${code}`),game);$('setup').classList.add('hidden');$('host').classList.remove('hidden');onValue(ref(db,`games/${code}`),s=>{game=s.val();render()})}
async function start(level){if(!code)return;await update(ref(db,`games/${code}`),{level,index:0});}
async function next(){if(!code||!game||game.level==='waiting'||game.level==='finished')return;await update(ref(db,`games/${code}`),{index:(game.index||0)+1});}
$('create').onclick=create;document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>start(b.dataset.level));$('next').onclick=next;$('bonus').onclick=async()=>{if(!game)return;const u={};Object.entries(game.teams||{}).forEach(([id,t])=>u[`teams/${id}/score`]=(t.score||0)+50);await update(ref(db,`games/${code}`),u)};
window.addEventListener('beforeunload',()=>{});
