import {firebaseReady,db,ref,set,get,update,onValue,runTransaction} from './firebase.js';
import {TEAMS,TEAM_INFO,MCQ,ORDERS,ROBOTS} from './data.js';
const $=id=>document.getElementById(id); let code='',game=null,unsub=null,celebrated=false,timer=null;
const makeCode=()=>Math.random().toString(36).slice(2,7).toUpperCase();
const say=t=>$('setupMsg').textContent=t;
function teamRows(){return Object.entries(game?.teams||{}).sort((a,b)=>(b[1].score||0)-(a[1].score||0));}
function winner(){const rows=teamRows();if(!rows.length)return null;const max=rows[0][1].score||0;return rows.filter(([,t])=>(t.score||0)===max);}
function render(){if(!game)return;$('code').textContent=code;$('level').textContent=game.level==='waiting'?'WAITING':game.level==='finished'?'FINISHED':game.level.toUpperCase();$('phaseHint').textContent=game.level==='mcq'?'10 questions • 30 seconds each':game.level==='order'?'5 sequence challenges':game.level==='robot'?'5 robot missions':'Ready to launch';
 const rows=teamRows();$('scoreboard').innerHTML=rows.map(([id,t])=>{const names=Object.values(t.participants||{}).map(p=>p.name).filter(Boolean);const ch=t.challenge||{};const progress=game.level==='mcq'?`${Math.min((ch.index||0)+1,10)}/10`:game.level==='order'?`${Math.min((ch.index||0)+1,5)}/5`:game.level==='robot'?`${Math.min((ch.index||0)+1,5)}/5`:'';return `<div class="score"><span class="dot">${TEAM_INFO[id].emoji}</span><div><b>${TEAM_INFO[id].name} Team</b><small>${names.length?names.join(', '):'No participants'}${progress?` • ${progress}`:''}</small></div><strong>${t.score||0}</strong></div>`}).join('');
 const win=winner();$('leader').textContent=win?win.map(([id,t])=>`🏆 ${TEAM_INFO[id].name} Team · ${t.score||0} points`).join('  •  '):'';
 const participants=[];rows.forEach(([id,t])=>Object.values(t.participants||{}).forEach(p=>participants.push({team:id,name:p.name})));$('participants').innerHTML=participants.length?participants.map(p=>`<span class="participant"><i>${TEAM_INFO[p.team].emoji}</i>${escapeHtml(p.name)}</span>`).join(''):'<span class="muted">Waiting for students to join…</span>';
 let prompt='Create a game to begin.';if(game.level==='mcq')prompt=`Question ${Math.min((game.teams?.[rows[0]?.[0]]?.challenge?.index||0)+1,10)} of 10 • Each team has 30 seconds per question.`;if(game.level==='order')prompt=`In Order • Teams are progressing independently through 5 sequences.`;if(game.level==='robot')prompt=`Robot Game • Teams are progressing independently through 5 missions.`;if(game.level==='finished')prompt='🎉 Team Challenge complete. The highest-scoring team is the winner.';$('hostPrompt').textContent=prompt;
 if(game.level==='finished'&&!celebrated){celebrated=true;showCelebration();}
 if(game.level!=='finished')celebrated=false;
 clearInterval(timer); timer=null; if(game.level==='mcq'){timer=setInterval(()=>{const first=Object.values(game.teams||{})[0]?.challenge?.startedAt; const left=Math.max(0,300000-(Date.now()-(first||Date.now()))); $('globalTimer').textContent=`${String(Math.floor(left/60000)).padStart(2,'0')}:${String(Math.ceil((left%60000)/1000)).padStart(2,'0')}`;},250);} else $('globalTimer').textContent='—';
}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
async function create(){if(!firebaseReady)return say('Firebase is not configured. Add your project values to firebase-config.js first.');code=makeCode();const n=+$('teamCount').value;const teams={};TEAMS.slice(0,n).forEach(t=>teams[t]={score:0,participants:{},challenge:{index:0,startedAt:null,questionStartedAt:null,completed:false}});game={level:'waiting',teams};await set(ref(db,`games/${code}`),game);$('setup').classList.add('hidden');$('host').classList.remove('hidden');if(unsub)unsub();unsub=onValue(ref(db,`games/${code}`),s=>{game=s.val();render()});}
async function start(level){if(!code||!game)return;if(level==='finished')return finish();const now=Date.now();const patch={level};const teamPatch={};Object.keys(game.teams||{}).forEach(id=>teamPatch[`teams/${id}/challenge`]={index:0,startedAt:now,questionStartedAt:now,completed:false});Object.assign(patch,teamPatch);await update(ref(db,`games/${code}`),patch);}
async function finish(){if(!code)return;await update(ref(db,`games/${code}`),{level:'finished',finishedAt:Date.now()});}
$('create').onclick=create;document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>start(b.dataset.level));$('bonus').onclick=async()=>{if(!game)return;const u={};Object.entries(game.teams||{}).forEach(([id,t])=>u[`teams/${id}/score`]=(t.score||0)+50);await update(ref(db,`games/${code}`),u)};
function showCelebration(){const wins=winner();if(!wins)return;const names=wins.flatMap(([id,t])=>Object.values(t.participants||{}).map(p=>p.name)).filter(Boolean);$('winnerTitle').textContent=wins.length>1?'Joint Winners!':`${TEAM_INFO[wins[0][0]].emoji} ${TEAM_INFO[wins[0][0]].name} Team Wins!`;$('winnerNames').textContent=names.length?`Players: ${names.join(', ')}`:'Great teamwork!';$('winnerScore').textContent=`${wins[0][1].score||0} points`;$('celebration').classList.remove('hidden');makeConfetti();}
$('closeCelebration').onclick=()=>$('celebration').classList.add('hidden');
function makeConfetti(){const box=$('confetti');box.innerHTML='';for(let i=0;i<90;i++){const s=document.createElement('i');s.className='confetti';s.style.left=Math.random()*100+'%';s.style.animationDelay=Math.random()*1.4+'s';s.style.setProperty('--x',(Math.random()*160-80)+'px');s.style.setProperty('--r',(Math.random()*720-360)+'deg');box.appendChild(s)}}
